instances:

  recom_sms:
    model: awi/recom_sms

  recom_light_attenuation:
    model: awi/recom_light_attenuation
    coupling:
      phytoplankton_chlorophyll: recom_sms/phytoplankton_chlorophyll
      diatom_chlorophyll: recom_sms/diatom_chlorophyll
